version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - /var/log/serverlogs:/var/log/nginx
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    volumes:
     - /var/lib/docker/volumes/esdata/_data:/usr/share/elasticsearch/config/data:ro
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.2
    command: filebeat -e -strict.perms=false
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      KIBANA_HOSTS: http://kibana:5601
    volumes:
      - /var/lib/docker/volumes/filebeat_data/_data:/usr/share/filebeat/data:ro
      - /var/log/serverlogs:/usr/share/filebeat/logs
    links:
       - elasticsearch
       - kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme%
    ports:
      - 5601:5601

    depends_on:
      - elasticsearch
    links:
      - elasticsearch
